name: Seq CI (fork)

on:
  push:
    branches: [ yasakova_t_sort_seq ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++ make

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build seq tests
        run: cmake --build build --target seq_tests -j2

      - name: Run seq tests
        run: ctest --test-dir build -R '^seq' --output-on-failure
